
# init autogenerated folder
rm -rf autogenerated/
mkdir autogenerated/

# generate gRPC calculator class
python \
-m grpc_tools.protoc \
-I. \
--proto_path=./proto \
--python_out=./autogenerated \
--grpc_python_out=./autogenerated \
calculator.proto


# python \
# -m grpc_tools.protoc \
# -I. \
# --python_out=./autogenerated \
# --grpc_python_out=./autogenerated \
# proto/calculator.proto


# # generate the gRPC hello class
# python \
# -m grpc_tools.protoc \
# -I. \
# --python_out=./generated_pb2 \
# --grpc_python_out=./generated_pb2 \
# hello.proto